### ISSUE TITLE
(TODO) Sachen die als nächstes gemacht werden müssen

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#77]
Liste mit Todos
### Bugs + Kleinigkeiten
- [x] #136 Radiobuttons (sehr WICHTIG)
- [x] #52 UpdateChecker
- [x] #135 Negative Zeit...
- [ ] #98 macOS Protokoll (wontfix?)
- [x] #74 Alert box Widget
### Große Sachen
- [ ] #103 Querverweise etc.
- [x] #92 Profil, #91 Admin (In Arbeit) (fixed by #127)
  - [ ] #133 Passwort ändern
- [ ] E-Mail Integration... (IMAP + SMTP)
- [ ] #34 Serienbrief
- [ ] #36 TN-Liste
### Texte
- [ ] #7 Hilfe
- [x] #94 Impressum + Infotext
- [ ] #90 Infotext

### Nice to Have
- [ ] #95 Maps
- [ ] #88 Crash handler
- [ ] #114 Build Rewrite (als Vue cli Plugin)
- [ ] #37 AK-Person rewrite

**Comment by mathe42** [comment]
@tobikrs Bitte bei neuen Issues diese auch hier eintragen...

**Comment by mathe42** [comment]
Ich habe die Projekte aktualisiert. Daher ist diese liste nicht ntwendig
